apiVersion: v1
kind: Secret
metadata:
  name: stock-closing-price-secret
  namespace: safe-schooling
type: Opaque
stringData:
  connection-string: "Encrypt=True;TrustServerCertificate=True;Database=SafeSchooling;Server=db.cyut.edu.tw;User ID=stockul;Password='s7dJr'"
